version: '3'
services:
  service-registry:
    image: service-image
    container_name: service-registry-container
    expose:
      - 8761
    ports:
      - "8761:8761"
    environment:
      server.port: 8761  
    networks:
      - kartiks-network
  
  config-server:
    image: config-server
    container_name: config-service-container
    expose:
      - 8888
    ports:
      - "8888:8888"
    environment:
      server.port: 8888
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
  api-gateway:
    image: api-gateway
    container_name: api-gateway-container
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      server.port: 8080
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
      - config-server

  movie-catalog-service:
    image: catalog-image
    container_name: catalog-service-container
    expose:
      - 8090
    ports:
      - "8090:8090"
    environment:
      server.port: 8090
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
      - config-server
      - api-gateway

  movie-streaming-service:
    image: streaming-image
    container_name: streaming-service-container
    expose:
      - 8091
    ports:
      - "8091:8091"
    environment:
      server.port: 8091
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
      - config-server
      - api-gateway

 

  
networks:
  kartiks-network: