version: '3'
services:
  service-registry:
    image: kartiks/service-image
    container_name: service-registry-container
    ports:
      - "8761:8761"
    environment:
      server.port: 8761  
    networks:
      - kartiks-network
  
  config-server:
    image: kartiks/config-server
    container_name: config-service-container
    ports:
      - "8888:8888"
    environment:
      server.port: 8888
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
  api-gateway:
    image: kartiks/api-gateway
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    environment:
      server.port: 8080
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry

  movie-catalog-service:
    image: kartiks/catalog-image
    container_name: catalog-service-container
    ports:
      - "8090:8090"
    environment:
      server.port: 8090
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
      - config-server
      - api-gateway

  movie-streaming-service:
    image: kartiks/streaming-image
    container_name: streaming-service-container
    ports:
      - "8091:8091"
    environment:
      server.port: 8091
      eureka.client.enabled: 'true'
      eureka.host: service-registry
      eureka.instance.preferIpAddress: 'true'
    networks:
      - kartiks-network
    depends_on:
      - service-registry
      - config-server
      - api-gateway

 

  
networks:
  kartiks-network: